#!/bin/sh

# PROVIDE: sway
# REQUIRE: dbus
# KEYWORD: shutdown

. /etc/rc.subr

name="sway"
rcvar="sway_enable"

start_cmd="sway_start"
stop_cmd="sway_stop"
status_cmd="sway_status"

load_rc_config $name

: ${sway_enable="NO"}
: ${sway_command="/usr/local/bin/sway"}
: ${sway_daemon_pidfile="/var/run/sway_daemon.pid"}
: ${sway_program_pidfile="/var/run/sway_program.pid"}
: ${WLR_BACKENDS="${sway_backends:-headless}"}

sway_start() {
    set -x
    echo "Starting $name"
    export WLR_BACKENDS="$WLR_BACKENDS"
    export WLR_LIBINPUT_NO_DEVICES=1
    export XDG_RUNTIME_DIR="/var/run/xdg/root"
    export XDG_CONFIG_HOME="/usr/local/etc/sway"
    export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

    rm -rf "$XDG_RUNTIME_DIR"
    mkdir -p "$XDG_RUNTIME_DIR"
    chmod 0700 "$XDG_RUNTIME_DIR"

    /usr/sbin/daemon -r -P "$sway_daemon_pidfile" -p "$sway_program_pidfile" -- $sway_command >/dev/null 2>&1 &
    set +x
}

sway_stop() {
    set -x
    echo "Stopping $name"

    local daemon_pid=""
    if [ -f "$sway_daemon_pidfile" ]; then
        daemon_pid=$(cat "$sway_daemon_pidfile")
    fi

    local program_pid=""
    if [ -f "$sway_program_pidfile" ]; then
        program_pid=$(cat "$sway_program_pidfile")
    fi

    kill -9 $daemon_pid $program_pid >/dev/null 2>&1

    rm -f "$sway_daemon_pidfile"
    rm -f "$sway_program_pidfile"

    set +x
}

sway_status() {
    set -x

    if [ -f "$sway_daemon_pidfile" ]; then
        echo "$name is running"
    else
        echo "$name is not running"
    fi

    set +x
}

run_rc_command $1
